# Generated by Django 4.1.5 on 2023-01-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supertype',
            name='type',
            field=models.CharField(choices=[('Hero', 'Hero'), ('Villian', 'Villian')], default='Hero', max_length=7),
        ),
    ]
